apiVersion: apps/v1
kind: Deployment
metadata:
    name: server2-deployment
spec:
    replicas: 3
    selector:
        matchLabels:
            component: server2
    template:
        metadata:
            labels:
                component: server2 # should match the selector above
        spec:
            containers:
                - name: server2 # this is the name of the container we wish to keep
                  image: lakshyajit165/k8s_demo_server2
                  ports:
                      - containerPort: 5002
